version: "3"
services:
  redis1:
    image: redis:latest
    container_name: redis1
    ports:
      - 6379:6379
  redis2:
    image: redis:latest
    container_name: redis2
    ports:
      - 6380:6379
  redis3:
    image: redis:latest
    container_name: redis3
    ports:
      - 6381:6379
  redis4:
    image: redis:latest
    container_name: redis4
    ports:
      - 6382:6379
  redis5:
    image: redis:latest
    container_name: redis5
    ports:
      - 6383:6379
  
  mongo1:
    image: mongo:latest
    container_name: mongo1
    ports:
      - 27017:27017
      